### ISSUE TITLE
Error: package 'use-package-' is unavailable

### ISSUE THREAD

**Issue by altvec** [freetonik/castlemacs#1]
I'm doing clean install via homebrew:

```
brew tap railwaycat/emacsmacport
brew cask install emacsmacport
git clone https://github.com/freetonik/castlemacs ~/.emacs.d
```

After launching Emacs I've got an error:

```
error: Package 'use-package-' is unavailable
Opening TLS connection with ‘gnutls-cli --x509cafile /etc/ssl/cert.pem -p 443 melpa.org --protocols ssl3’...failed
```

Looks like this version of Emacs is using GnuTLS library. After installing `gnutls` via homebrew the issue was resolved. Perhaps this should be mentioned in the "Installing dependencies" section of the documentation?

**Comment by freetonik** [comment]
Thanks for catching that! I guess I had this installed as a dependency of something else since forever.

https://github.com/freetonik/castlemacs/commit/25506e22c8883b7b47d89dc59ce1fe9c024d896e
