### ISSUE TITLE
Typo in custom.el

### ISSUE THREAD

**Issue by bwl** [freetonik/castlemacs#10]
Should say Castlemacs.

Not sure how to handle as custom.el theoretically should not be updated, but I think it's worth noting.

https://github.com/freetonik/castlemacs/blob/b48af25b039fe44f831b8003623bbce27ee63a37/custom.el#L2

**Comment by freetonik** [comment]
Yeah, it's a pickle... I guess it should be okay for the small number of early adopters to pull that change, since it's only a one line.
