### ISSUE TITLE
Why multiple-cursors?

### ISSUE THREAD

**Issue by zenshinji** [freetonik/castlemacs#13]
This is not typical MacOS functionality in Notes or TextEdit or most other editors, so it seems out of place as a default here. I understand why some people like and prefer it, but it is hardly a broadly embraced standard.

Please reconsider it as a default.

**Comment by freetonik** [comment]
This is a common and an important built-in feature of the most popular GUI editors: Sublime Text, VS Code, Atom. The idea of Castlemacs is to provide an experience similar to these editors, while maintaining the core principles. 

Almost none of the features of Castlemacs are typical in Notes or TextEdit.

I believe multiple cursors to be an essential tool, and it will stay.
