### ISSUE TITLE
Reloading init.el gives error message

### ISSUE THREAD

**Issue by apc** [freetonik/castlemacs#19]
Whenever I load `init.el` after startup I get this warning

```
 Couldn’t find minor-mode-alist inside ‘mode-line-modes’
```

The error seems to come from `rich-minority`. But I don't quite understand what triggers the warning only when reloading `init.el`. 

EDIT: apparently this is the intended behavior. See here: https://github.com/Malabarba/rich-minority/issues/2

**Comment by freetonik** [comment]
Hey,
is this still happening with the latest version of `rich-minority`?

**Comment by apc** [comment]
Sorry, I haven't been using Castlemacs lately, and moved on to my own (Castlemacs-inspired!) config. But for what is worth, it's been a while since I ran into this issue, and setting things up like so helped: 

```
(use-package rich-minority
  :defer nil
  :config
  (unless rich-minority-mode ;; This prevents us from getting an error message upon re-loading init.el
  (rich-minority-mode 1))
  (setf rm-blacklist ""))
```

**Comment by freetonik** [comment]
Cool, thank you!
