### ISSUE TITLE
transparent titlebar

### ISSUE THREAD

**Issue by takaxp** [freetonik/castlemacs#2]
Hi.
I like your new Emacs definition as `a framework for creating any text editor you want` :)

BTW, from Emacs 26.1 on macOS, the titlebar can be transparent like:

![screen shot 2018-09-23 at 12 29 10](https://user-images.githubusercontent.com/136673/45923865-59bfac00-bf2c-11e8-8390-b1badcf4c9fd.png)

with the following settings.

```lisp
(when (memq window-system '(mac ns))
  (add-to-list 'default-frame-alist '(ns-appearance . light)) ;; {light, dark}
  (add-to-list 'default-frame-alist '(ns-transparent-titlebar . t)))
```

I believe these options will make castlemacs more modern.

Thanks.

**Comment by freetonik** [comment]
Hi!

This didn't work in [Emacs port](https://github.com/railwaycat/homebrew-emacsmacport), unfortunately. But did work in https://emacsformacosx.com/ 

Any ideas how to fix that?

**Comment by takaxp** [comment]
Hi!

If you use a dark theme with `'(ns-apperance . dark)` then you can see the colored titlebar.

EMP (Emacs Mac Port):
![screen shot 2018-09-24 at 23 35 08](https://user-images.githubusercontent.com/136673/45959432-d9e13100-c054-11e8-9a54-3bbcd92f2a91.png)

NS:
![screen shot 2018-09-25 at 0 00 37](https://user-images.githubusercontent.com/136673/45959959-119ca880-c056-11e8-967a-814476d74a14.png)


If you cannot see any changes in your Emacs Mac Port build version, then just restrict the setting to NS build version :)

```
(when (eq window-system 'ns)
  (add-to-list 'default-frame-alist '(ns-appearance . light)) ;; {light, dark}
  (add-to-list 'default-frame-alist '(ns-transparent-titlebar . t)))
```

**Comment by takaxp** [comment]
And homebrew-emacs-plus project would help you.

- https://github.com/d12frosted/homebrew-emacs-plus
- https://github.com/d12frosted/homebrew-emacs-plus#options

**Comment by freetonik** [comment]
Turns out this feature is disabled by default in emacsport https://github.com/railwaycat/homebrew-emacsmacport/wiki/Natural-Title-Bar And the pre-built binary I'm recommending in the README is built without `--with-natural-title-bar` option.

I will update the config and update the README accordingly. 

Thank you.

**Comment by freetonik** [comment]
Forgot to close in commit message.

[This](https://github.com/freetonik/castlemacs/commit/91e75d23592ce46015e0e76aa2b494065df7a74b) closes the issue.

Thank you!
