### ISSUE TITLE
Failed to install magit

### ISSUE THREAD

**Issue by avioli** [freetonik/castlemacs#26]
Following the installation guide I'm getting the following in the `*scratch*` buffer on every re-start after I clone the repo and replace `~/.emacs.d/`:

```
⛔ Error (use-package): Failed to install magit: Failed to verify signature: "compat-30.0.0.0.tar.sig"
⛔ Error (use-package): Cannot load magit
```

and the following in the `*Warnings*` buffer:

```
Failed to verify signature compat-30.0.0.0.tar.sig:
No public key for 645357D2883A0966 created at 2024-07-09T07:05:02+1000 using EDDSA
Command output:
gpg: keyblock resource '/Users/avioli/.emacs.d/elpa/gnupg/pubring.kbx': No such file or directory
gpg: Signature made Tue  9 Jul 07:05:02 2024 AEST
gpg:                using EDDSA key 0327BE68D64D9A1A66859F15645357D2883A0966
gpg: Can't check signature: No public key
```

**Comment by freetonik** [comment]
I've tried to reproduce this on a fresh install, and couldn't. Could you provide some more info on your system: which version of emacs and macOS do you have?

This might be related: https://stackoverflow.com/questions/58202993/emacs-failed-to-verify-signature-archive-contents-sig

**Comment by avioli** [comment]
I've followed your installation guide, which stated to go to https://emacsformacosx.com/ and download it from there.

```
Emacs Version 29.4-1
Universal Binary (96.238 MB) Released 2024-08-02
```

My macOS is Ventura `13.6.9 (22G830)`

I'll try what is outlined in that SO post and come back if that helped.

**Comment by avioli** [comment]
Ok. `M-x package-refresh-contents` did the trick. I restarted emacs then and it installed magit fine. Then I restarted it once again and it all seems operational.

Thanks for the hint.

Feel free to maybe mention this in the installation guide, although it might not be necessary for everyone.
