### ISSUE TITLE
Prevent font errors

### ISSUE THREAD

**Issue by Compro-Prasad** [freetonik/castlemacs#5]
Menlo is a font not available by default on many systems apart from Mac. So, I would suggest to set this font only when system is `darwin`. `system-type` might be useful in such a case.

**Comment by takaxp** [comment]
It could be checked to see `(font-family-list)`.

**Comment by Compro-Prasad** [comment]
Yup. Its as simple as:
```elisp
(when (member "menlo" (font-family-list))
  (set-face-attribute 'default nil :font "Menlo 15"))
```
@freetonik Just check if the name is correct and it should be good to go.

**Comment by freetonik** [comment]
Thanks!
