### ISSUE TITLE
What castlemacs shouldn't do?

### ISSUE THREAD

**Issue by Compro-Prasad** [freetonik/castlemacs#6]
What kind of feature requests are you looking for? Language specific features, tools, bug fixes or something else?

I am asking this because castlemacs is minimalistic.

**Comment by freetonik** [comment]
Hi,

- bug fixes
- usability and UI improvements
- language specific features, but not going too far into the IDE land. Basically, Castlemacs should eventually support whatever Sublime Code supports out of the box: basic modes for popular languages and frameworks, linting, some sort of dumb-jumping, etc. I'd like to draw comparisons with VS Code, but it gradually becomes way to bloated IMO.
