### ISSUE TITLE
Where to put private pre init configs

### ISSUE THREAD

**Issue by Pilgrim1379** [freetonik/castlemacs#8]
Hi and thanks for your effort. I'm looking for a way to add custom settings that will read before init.el or very early in init.el. For example startup benchmarking settings, initial and default frame location settings etc.

At the moment it seems to me like early-init.el will be the place but I don't know it update will overwrite this file.

**Comment by freetonik** [comment]
Hi,

Since we have `init.el` + `private.el`, I guess we should have `early-init.el` + `early-init-private.el`. What do you think?

**Comment by takaxp** [comment]
In my case, I use `.emacs` that is a traditional way.
For example, I put some settings and loading init.el explicitly in my `.emacs`.

```lisp
;; pur your setting for benchmarking settings before loading init.el
(defconst my-profiler-p nil
  "If non-nil, use built-in profiler.el.")
(when my-profiler-p
  (profiler-start 'cpu+mem))
(setq custom-file (expand-file-name "custom.el" user-emacs-directory))

;; load init.el
(load "~/Dropbox/emacs.d/config/init.el" nil t)

;; report profile result if my-profiler-p is non-nil
(when my-profiler-p
    (profiler-report))
```

**Comment by Pilgrim1379** [comment]
> Hi,
> 
> Since we have `init.el` + `private.el`, I guess we should have `early-init.el` + `early-init-private.el`. What do you think?

Yeah I like the semantics of `early-init-private.el`. 

It probably should come with a caveat in the `README` that no package specific settings can be included in that file since `use-package` would probably not have been bootstraped yet when it is processed?

**Comment by freetonik** [comment]
Yes, you're right. It's time to include a whole section on both private config files. I'll work on this later this week.
